return {
    en = {
        status = {
            kicked = '&&&1 بن شده در این گروه',
            left = '&&&1 از گروه رفته و یا اخراج شده',
            administrator = '&&&1ادمین هستش',
            creator = '&&&1 سازنده گروه هست',
            unknown = 'این فرد در گروه مقامی ندارد',
            member = '&&&1 فرد معمولی هستش'
        },
        getban = {
            header = '*Global stats* for ',
            nothing = '`Nothing to display`',
            kick = 'Kick: ',
            ban = 'Ban: ',
            tempban = 'Tempban: ',
            flood = 'حذف شد به خاطر اتک زدن: ',
            warn = 'حذف شد به خاطر اخطار گرفتن: ',
            media = 'حذف شد به خاطر ارسال مدیا: ',
            arab = 'حذف شد به دلیل فارسیچت کردن: ',
            rtl = 'حذف ار تی ال: ',
            kicked = '_اخراج شد!_',
            banned = '_بن شد!_'
        },
        bonus = {
            general_pm = '_من\'فرستادم تو پیویت گل من_',
            no_user = 'I\'ve never seen this user before.\nIf you want to teach me who he is, forward me a message from him',
            the_group = 'گروهه دیگه',
            adminlist_admin_required = 'من\'تو گروه هنوز ادمین نشدم.\n*فقط ادمینا میتونن به این چیزا دسترسی داشته باشن 😆*',
            settings_header = 'Current settings for *the group*:\n\n*Language*: `&&&1`\n',
            reply = '*Reply to someone* to use this command, or write a *username*',
            too_long = 'This text is too long, I can\'t send it',
            msg_me = '_اول تو بیا پیوی😐_',
            menu_cb_settings = 'Tap on an icon!',
            menu_cb_warns = 'Use the row below to change the warns settings!',
            menu_cb_media = 'فشار بده رو سوییچ!',
            tell = '*ایدی گروه🔩*: &&&1',
        },
        not_mod = 'You are *not* a moderator',
        breaks_markdown = 'This text breaks the markdown.\nMore info about a proper use of markdown [here](https://telegram.me/GroupButler_ch/46).',
        credits = '*Some useful links:*',
        extra = {
            setted = '&&&1 command saved!',
			usage = 'Write next to /extra the title of the command and the text associated.\nFor example:\n/extra #motm stay positive. The bot will reply _\'Stay positive\'_ each time someone writes #motm',
            new_command = '*دستور جدید تنظیم شد!*\n&&&1\n&&&2',
            no_commands = 'دستوری تنظیم نشده است💈',
