local triggers2 = {
	'^/a(init)$',
	'^/a(stop)$',
	'^/a(backup)$',
	'^/a(bc) (.*)$',
	'^/a(bcg) (.*)$',
	'^/a(save)$',
	'^/a(commands)$',
	'^/a(stats)$',
	'^/a(lua)$',
	'^/a(lua) (.*)$',
	'^/a(run) (.*)$',
	'^/a(log) (del) (.*)',
	'^/a(log) (del)',
	'^/a(log) (.*)$',
	'^/a(log)$',
	'^/a(admin)$',
	'^/a(block) (%d+)$',
	'^/a(block)$',
	'^/a(unblock) (%d+)$',
	'^/a(unblock)$',
	'^/a(isblocked)$',
	'^/a(ping redis)$',
	'^/a(leave) (-%d+)$',
	'^/a(leave)$',
	'^/a(post) (.*)$',
	'^###(forward)',
	'^/a(reset) (.*)$',
	'^/a(reset)$',
	'^/a(send) (-?%d+) (.*)$',
	'^/a(send) (.*)$',
	'^/a(adminmode) (%a%a%a?)$',
	'^/a(delflag)$',
	'^/a(usernames)$',
	'^/a(api errors)$',
	'^/a(rediscli) (.*)$',
	'^/a(updatewelcome)$',
	'^/a(movechat) (-%d+)$',
	'^/a(redis backup)$',
	'^/a(group info) (-?%d+)$',
	'^/a(fill media)$',
	'^/a(genlang)$',
	'^/a(genlang) (%a%a)$',
	'^/a(trfile) (%a%a)$',
	'^/a(trfile)$',
	'^/a(fixaction) (-%d+)$',
